### ISSUE TITLE
Proprietary license request

### ISSUE THREAD

**Issue by AlexisTM** [DentOpt/denmpc#2]
Dear @DentOpt,
We are interested in your controller at Unmanned Life but the license makes it impracticable to use. 

Indeed, using these controllers under GPL would require us to put all the control nodes open-source which would not be feasible.

If I am not incorrect, LGPL would be better for us:
* Keep the library open-source -> The library continues to grow
* Allows closed-source software to use it as a shared library -> More people/companies can use the software so the library can grow in PRs
* Requires to add the original author name in the closed-source software

**Comment by DentOpt** [comment]
Dear AlexisTm,

thanks for your interest in the denmpc framework.
Out of curiosity of a control engineer, may I ask what you are using it for?
I understand the inconvenience of GPL3 for you.
Unfortunately, the code is the intellectual property of the University of Luxembourg.
Consequently, the University decides about the license.
However, I know that they typically sell proprietary licenses.
So I can propose to contact the IP department, if you are interested in a paid solution.
Cheers,
Dentopt

**Comment by AlexisTM** [comment]
Dear @DentOpt, 
Thanks for the reply; I saw your library on the [ROS wiki](http://wiki.ros.org/denmpc) and checked it out. 
I planned to integrate this library and compare the performance with our in-house control system. As there is no insurance of success, we will simply not do it.
