### ISSUE TITLE
build error - missing file

### ISSUE THREAD

**Issue by LisaWeichsel** [DentOpt/denmpc#3]
Scheduler.h:19:46: fatal error: dentopt_nmpc_controller/VrepInfo.h: No such file or directory

**Comment by benjaminabruzzo** [comment]
I just initiated a pull request to the author.

There are a couple of places where dentopt_nmpc_controller is called in some of the header files, you can either change them manually to denmpc or wait for my pull to get incorporated.

**Comment by LisaWeichsel** [comment]
Thank you for your answer. I changed it manually, but I still get the error. 
Event.h:22:29: fatal error: denmpc/VrepInfo.h: No such file or directory

Do I have to install another ROS package to get the file VRepInfo.h ? 
I think its no part of the package denmpc.

**Comment by benjaminabruzzo** [comment]
No, Vrepinfo is a custom message defined in the denmpc package.  

Try cloning my tweaked version of the package, it should be linked through the pull request.



Benjamin

**Comment by DentOpt** [comment]
Hi Lisa and Benjamin,

I merged the changes of Benjamin to the master branch and verified the compilation on a separate system with ROS melodic. Please let me know if you have any further issues.
Thanks a lot for your feedback!

Cheers,
Jan
