### ISSUE TITLE
Turtel does not move

### ISSUE THREAD

**Issue by LisaWeichsel** [DentOpt/denmpc#5]
Hi there, 
I have another question to the tutorial:
I tried to run the tutorial and all works without errors, but the turtle does not move. Does anyone has the same problem ?

Thanks a los!

**Comment by DentOpt** [comment]
It only moves, if you give a new target position.
This is the StampedPose topic "/turtle1/desiredpose".
You can use the command line (rospub) or rqt to do so.
Do not forget to use an appropriate timestamp.
Cheers

**Comment by LisaWeichsel** [comment]
I tried to run the turtlesim_tutorial with the code of the master branch before. So now when using the turtlesim branch it works. But the same changes as in Benjamin's pull request are necessary to compile. Also the VRep msg has to be added to the CMAKEList.

Thanks for your answers.

**Comment by DentOpt** [comment]
Thanks, I will try to incorporate these changes in the turtlesim branch.
