### ISSUE TITLE
define custom systems

### ISSUE THREAD

**Issue by BernhardUAV** [DentOpt/denmpc#7]
Hi, 
Im trying to use this package to control a real customized drone with a gimbal attachment. The problem is now how  to define the system dynamics in the package. 

I think in the Ardrone example system dynamics were implemented in Matlab and then auto generated in cpp ? 

Is it enough to define them in the agent class ?

Kind regards
Bernahrd

**Comment by DentOpt** [comment]
1. In my case, I derived and exported the model from mathematica and identified the models in matlab.

2. Everything related to the dynamic model is implemented as an agent class in this case in (Ardrone_20170227.cpp, Ardrone_20170227.h). Therefore, changing the model there is sufficient (Just be aware, that in the example the parameters of the model are initialized in scenario.cpp)

Regarding the model:
The model included in the package is suitable for all drones, that have an internal attitude controller.
This means all drones to which you only send velocity commands (forward-, leftward-, upward-, heading-velocity). You just have to adjust the model parameters according to the drone. In this case 
you can find the associated model Ardrone parameters (-0.5092,1.458,-1,1,-5,1.3) in "scenario.cpp":
```
	double ardrone0_init_p[]={ //without tracking position
			-0.5092,1.458,-1,1,-5,1.3, // These are the model parameters
			0.0,0.0,0.0, 0.0,0.0, 0.0,0.0,0.0,0.0,  // These are the state penalty values
			1.0,1.0,0.3,1.0 // These are the control penalty values
};
```
If you only customized an Ardrone by adding a gimbal, the parameters will not vary a lot, as the internal controller of the drone is already rejecting a lot of the added disturbance. In this case, I would just try the current model parameters. However, if you use a fully customized drone, than you would need to identify the model parameters. You can do this with Matlab.
You can find a more detailed information about this procedure for the AR.Drone 2.0 (from experiments) and a DJI M100 (from simulator) in my thesis in chapter 3.7 Identification:
[Thesis](http://hdl.handle.net/10993/36965) 

If you want to fully change the dynamic model, than you have to derive 3 vector valued functions:
You need the system dynamics
`dx/dt= f(x,u)`
And the partial derivatives multiplied with a Lagrange-multiplier vector lambda
```
(d f(x,u)/d x) * lambda 
(d f(x,u)/d u) * lambda 
```
This looks more complicated than it actually is. For most simple dynamics you could easily derive this even from hand. 

Does this answer your question?

**Comment by DentOpt** [comment]
```	double ardrone0_init_p[]={ //without tracking position			-0.5092,1.458,-1,1,-5,1.3,			0.0,0.0,0.0, 0.0,0.0, 0.0,0.0,0.0,0.0,			1.0,1.0,0.3,1.0};```

**Comment by BernhardUAV** [comment]
Thanks for the fast answer! 

yes that is already helpful thanks. The only thing Im still wondering is, if I have got the new system dynamics in equations and function, do I need to define them only in the agents or are they also necessary in the controller. 
For example there is a 
void **Ardrone_20170227**::dfdxlambda(double  *out,double t, double *x, double *u, double *d, double *p, double *lambda)...

but also a 

void **Controller**::dfdxlambda(double *out,double t,double *x, double *u, double *d, double *p, double *lambda)

**Comment by DentOpt** [comment]
Hi,

You define the new system dynamics only in the agent Ardrone_20170227 class.

Detail:
What happens here is, that the controller base class is dynamically computing the necessary global OCP functions (e.g. Controller::dfdxlambda) out of all the scenario components (e.g. Ardrone_20170227::dfdxlambda).
So practically you only have to change the controller class, if you modify the solver algorithm. Otherwise I don't recommend touching it.
Best regards

**Comment by BernhardUAV** [comment]
Perfect thank you for the help. Ill implement the new dynamics and test it. 
I let you know how it works out. 

Best regards

**Comment by DentOpt** [comment]
Perfect. I'm looking forward to the results!

**Comment by DentOpt** [comment]
Hey Bernard, 
do you already have an update?
If there are no more direct issues from your side, I will close this issue.
Best regards,
Jan

**Comment by kosmastsk** [comment]
How about implementing the system dynamics for a robot totally different than a drone, e.g. an ackermann steering car or a tricycle. How is the proper way to generate the dynamics?
