### ISSUE TITLE
no cmd_vel published

### ISSUE THREAD

**Issue by benjaminabruzzo** [DentOpt/denmpc#8]
Have you tested the posted version of this code as-is? I just tried it on a different computer and an actual AR.Drone, but it still crashes.  The only change I made was the scenario.cpp file to use the topics that are relevant to my system.

If that is the only change, then I still get the stack smashing error in the constraint functions.

If I comment out the constraints then the mpc runs, but it does not generate any command messages for the UAV, all is publishes is the zero-zero-zero blank message instructing the AR.Drone to hover.

I don't think it is my configuration, but I am not sure what it issue is.  It seems like the other people trying your code seem to be successful.

**Comment by BernhardUAV** [comment]
Hello Benjamin,

In order to publish the messages I enabled the scheduler.run_control(0.01); in scenario.cpp: 

/****** Initialize Scheduler ******/
        Scheduler scheduler(argc,argv,controllerlist, eventlist);
        //
        scheduler.run_vrep(0.01);
        //scheduler.run_simulation(0.1,10);
        scheduler.run_control(0.01);

Unfortunately I have similar problems with the constrains, which make the control of the UAV really hard.

**Comment by DentOpt** [comment]
Hi,
thanks to you both for your feedback and sorry for the late response! 
I have originally tested the package on my system,
but I will try to test the system tomorrow on another system and give you an update.

Best regards,
Jan

**Comment by benjaminabruzzo** [comment]
This is addressed by issue #9
