### ISSUE TITLE
Has anyone else successfullly used this code to control an AR.Drone?

### ISSUE THREAD

**Issue by benjaminabruzzo** [DentOpt/denmpc#9]
I can't seem to get this code to work with either a real AR.Drone nor simulated in Gazebo.  Has anyone else been successful?

**Comment by DentOpt** [comment]
Hi,
I will try it tomorrow on another system and give you a heads up.
Best regards,
Jan

**Comment by benjaminabruzzo** [comment]
Thanks.  I’ll be trying it on a new install of 14.04.5 and ROS Indigo today.  Up until now I’ve been working on a 16.04.4/kinetic configuration.

Benjamin

**Comment by DentOpt** [comment]
Hi, 
to give an update. I am currently trying to validate in the following setup:
WSL - ros melodic - gazebo 7 - tum ardrone simulator.
However, I ran into issues to install the tum simulator,
but I hope to give you a heads up today, latest tomorrow.

**Comment by DentOpt** [comment]
I tested the code successfully with the tum ardrone simulator.
You can find the used package I have used under:
[https://github.com/DentOpt/ardrone_simulator_gazebo7](https://github.com/DentOpt/ardrone_simulator_gazebo7)

Unfortunately, I could not get Gazebo running on the WSL.
Therefore, I tested on indigo with gazebo 4.
Regarding the constraint error:
In the autogenerated code, the from the code generator automatically generated variables
e.g. double o[12] did have the wrong array sizes which lead to segmentation fault errors.
I furthermore resolved the initial start-up issues that benjaminabruzzo mentioned by modifying Ardrone_20170227.cpp.
In addition, I added two scenarios: 
```
ardrone_sensor_tracking.cpp
ardrone_pose_tracking.cpp
```
which can directly be used for controlling the ardrone of the ardrone_simulator_gazebo7 package (Check the readme there for more detailed information).

Does this solve your problems?
Best regards,
Jan

**Comment by benjaminabruzzo** [comment]
I will take a look at these today (if I have time) or definitely tomorrow and let you know.  Thank you so much for debugging this.

**Comment by benjaminabruzzo** [comment]
Worked like a charm.
